### PR TITLE
Add signature latte recipe

### PR DESCRIPTION
**Pull request by Smita6697**
please add signature latte recipe

### CODE REVIEW

**Comment by Smita6697** [comment]
close

**Comment by Smita6697** [comment]
Add signature latte recipe

**Review by SHIVANIPATNAIK1 — COMMENTED** [review]
Please modify the Menu file by adding the reference to the new signature_latte into the menu.

**Comment by Smita6697** [comment]
> Please modify the Menu file by adding the reference to the new signature_latte into the menu.

above changes have been made

**Review by SHIVANIPATNAIK1 — APPROVED** [review]
Approved

**Pull request merged**
